version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-dafino
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cloningan_gdrive
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret123
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
